// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7OZzmehReX0X_FT7-kNTXpcbm6Zkjbeg',
    appId: '1:918694146633:web:f1954dff62748dda824598',
    messagingSenderId: '918694146633',
    projectId: 'ciloka-app',
    authDomain: 'ciloka-app.firebaseapp.com',
    storageBucket: 'ciloka-app.firebasestorage.app',
    measurementId: 'G-6JLP7VK3XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1n_qq6ZuityT60MpW7oe3so63P2rnhqs',
    appId: '1:918694146633:android:168361fab35bdbbd824598',
    messagingSenderId: '918694146633',
    projectId: 'ciloka-app',
    storageBucket: 'ciloka-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL5K2AG8TsSD26uaLdJR2PnnlPN-NWWlE',
    appId: '1:918694146633:ios:69ead05a47bc0cb8824598',
    messagingSenderId: '918694146633',
    projectId: 'ciloka-app',
    storageBucket: 'ciloka-app.firebasestorage.app',
    iosClientId: '918694146633-a8oplh0q12g0ep8e5h6c633oes691qcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.cilokaApp',
  );
}
